### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by luckylat** [luckylat/StreamDeck-BookShelf#1]
- [ ] v1
  - [ ] Make the book link
    - [ ] Get Book data from Kindle Native Application (luckylat/kindleparser)
    - [ ] Get Book image (from google book API)
    - [ ] Make Button
- [ ] v2
  - [ ] Get new window to show books
